ovh-ux/ovh-api-services

src/deskaas/deskaas.lexi.service.js
src/deskaas/deskaas.service.js

Hotfix(eslint): code style

---

src/metrics/metrics.service.lexi.js

Hi everyone!
I'm working on the Metrics Data Platform project, and I would like to add the new path we added on APIv6 to change Quota 😃

feat(metrics): adding new route to change quota on new service

---

src/dbaas/logs/logs.lexi.service.js

Added serviceInfos APIs

---

.bowerrc

As recommended here https://gist.github.com/sheerun/c04d856a7a368bad2896ff0c4958cb00
Signed-off-by: Benjamin Coenen <benjamin.coenen@corp.ovh.com>

chore(bower): add bowerrc file to use the right registry

---

src/dedicatedCloud/dedicatedCloud.v6.service.js
src/dedicatedCloud/task/dedicatedCloud-task.v6.service.js

Add route for /dedicatedCloud/{serviceName}/globalTasks

feat(dedicatedCloud): add global task route

---

src/kube/kube.v6.service.js

* Add route for GET /kubeconfig
* add route for PUT /kube/:serviceName

feat(kube): add routes for kubeconfig and put method

---

package-lock.json
src/veeamEnterprise/veeamEnterprise.service.js
src/veeamEnterprise/veeamEnterprise.v6.service.js

* Add routes for veeam enterprise (https://api.ovh.com/console/#/veeam/veeamEnterprise)

feat(veeamEnterprise): add routes for veeam enterprise

---

src/connectivity/eligibility/connectivity-eligibility.service.js
src/connectivity/eligibility/connectivity-eligibility.v6.service.js

New route to access to building details for fiber migration (call APIv6)

feat(fiber): add route for building details

---

src/screenshot/screenshot.aapi.service.js
src/screenshot/screenshot.service.js

9271c3b : feat(screenshot): add screenshot aapi
ref: OM-171
/cc @jleveugle @frenautvh @antleblanc

feat(screenshot): add screenshot aapi

---

src/xdsl/xdsl.v6.service.js

fix: remove cache on modem tasks list

---

src/email/exchange/service/email-exchange-service.service.js
src/email/exchange/service/email-exchange-service.v6.service.js

feat(email.exchange): add apiv6 basic routes

---

src/pack/xdsl/pack-xdsl.v6.service.js

feat(migration): add endpoint to retrieve subservices to delete

---

src/xdsl/modem/firmware/xdsl-modem-firmware.v6.services.js

feat(firmware): transform the response of the call api

---

src/xdsl/modem/reset/xdsl-modem-reset.v6.service.js

feat(reset_modem): add method post for modem reset endpoint call

---

src/xdsl/modem/blocIp/xdsl-modem-blocIp.service.js
src/xdsl/modem/blocIp/xdsl-modem-blocIp.v6.services.js
src/xdsl/modem/callWaiting/xdsl-modem-callWaiting.service.js
src/xdsl/modem/callWaiting/xdsl-modem-callWaiting.v6.services.js
src/xdsl/modem/contentSharing/xdsl-modem-contentSharing.service.js
src/xdsl/modem/contentSharing/xdsl-modem-contentSharing.v6.services.js
src/xdsl/modem/ftp/xdsl-modem-ftp.service.js
src/xdsl/modem/ftp/xdsl-modem-ftp.v6.services.js
src/xdsl/modem/ipsecAlg/xdsl-modem-ipsecAlg.service.js
src/xdsl/modem/ipsecAlg/xdsl-modem-ipsecAlg.v6.services.js
src/xdsl/modem/sipAlg/xdsl-modem-sipAlg.service.js
src/xdsl/modem/sipAlg/xdsl-modem-sipAlg.v6.services.js
src/xdsl/modem/upnp/xdsl-modem-upnp.service.js
src/xdsl/modem/upnp/xdsl-modem-upnp.v6.services.js
src/xdsl/modem/xdsl-modem.service.js

feat(modem-change): add call api for modem change

---

src/kube/kube.v6.service.js

allow customer to set update policy from UI

feat(K8S): update policy

---

src/cdn/dedicated/cdn-dedicated.v6.service.js
src/cdn/dedicated/domains/cdn-dedicated-domains.service.v6.js

Hello,
This pull-request add the both lexi calls to allow CDN customers to follow their logs in real time.
Thanks for your review, merge & prod time.
Signed-off-by: Pierre De Paepe <pierre.de-paepe@corp.ovh.com>

feat(CDN): allow customers to get their logs

---

src/cloud/project/flavor/cloud-project-flavor.v6.service.js

add clear cache and clear query cache methods
resolves MBP-329

fix(flavor): add clear cache

---

src/order/order.service.js
src/order/upgrade/order-upgrade.service.js
src/order/upgrade/privateCloud/order-upgrade-privateCloud.service.js
src/order/upgrade/privateCloud/order-upgrade-privateCloud.v6.service.js

feat: add calls to order PCC

---

src/universes/universes.aapi.service.js
src/universes/universes.service.js

feat(universes): add aapi call for available universes

---

src/cloud/project/storage/cloud-project-storage.aapi.service.js
src/cloud/project/storage/cloud-project-storage.service.js

a5e26a6 — feat(cloud): add cloud project storage aapi service
/cc @jleveugle @marie-j

feat(cloud): add cloud project storage aapi service

---

src/domain/configurations/obfuscatedEmails/domain-configurations-obfuscatedEmails.v6.service.js

fix(domain.configurations): add correct response type for put method

---

src/cloud/project/instance/cloud-project-instance.service.js
src/cloud/project/instance/interface/cloud-project-instance-interface.service.js
src/cloud/project/instance/interface/cloud-project-instance-interface.v6.service.js

73abeab — feat: add instance interface v6 service
/cc @jleveugle @marie-j

feat: add instance interface v6 service

---

src/service/services.aapi.service.js
src/service/services.service.js

ce244df — feat: add service aapi

feat: add service aapi

---

src/me/order/me-order.v6.service.js

2fa0e38 — feat(me.order.v6): add pay endpoint

feat(me.order.v6): add pay endpoint

---

src/cloud/project/containerRegistry/users/cloud-project-containerRegistry-users.v6.service.js

remove query body

---

src/cloud/project/instance/cloud-project-instance.v6.service.js

8f68baf — fix: applicationAccess return an object
ref: MANAGER-2706
```json
{
"status": "ok",
"accesses": [
{
"url": "https://url.ext:port/",
"type": "wordpress",
"password": "",
"login": ""
},
{
"url": "https://url.ext:port/",
"type": "phpmyadmin",
"password": "password",
"login": "login"
}
]
}
```

fix: applicationAccess return an object

---

src/cloud/project/cloud-project.v6.service.js
src/cloud/project/user/cloud-project-user.service.js
src/cloud/project/user/role/cloud-project-user-role.service.js
src/cloud/project/user/role/cloud-project-user-role.v6.service.js

b21fe85 — feat: add cloud users roles services

feat: add cloud users roles services

---

src/analytics/platforms/node/platforms-node.service.js
src/analytics/platforms/node/platforms-node.v6.service.js
src/analytics/platforms/platforms.service.js
src/analytics/platforms/platforms.v6.service.js

Added APIs for fetching node details

feat(analytics): addition of nodes apis

---

src/me/agreements/me-agreements.v6.service.js

Query to get contract information with id

query agreement with contract id

---

src/cloud/cloud.v6.service.js
src/cloud/project/region/workflow/backup/cloud-project-region-workflow-backup.v6.service.js

Added PCI agreements endpoint and PCI auto backup endpoints

added cloud agreements and PCI auto backup end points

---

src/dedicatedCloud/user/dedicatedCloud-user.iceberg.service.js
src/dedicatedCloud/user/dedicatedCloud-user.service.js

This is based on `pccServicePacks`

feat: add support for Iceberg

---

src/me/order/me-order.v6.service.js

feat(me.order): get bill

---

rollup.config.js

refactor: globImport plugin configuration

---

src/cloud/project/kube/cloud-project-kube.v6.service.js

fix(kube-update): payload addition

---

package.json

2bb8de6 - build(package.json): add both version and postversion scripts

build(package.json): add both version and postversion scripts

---

package.json

0d3b79a - build(package.json): set right package version

build(package.json): set right package version

---

src/api/domain/domain.service.js
src/api/domain/options/domain-options.service.js
src/api/domain/options/domain-options.v6.service.js

feat(domain): options api addition

---

src/api/telephony/spare/telephony-spare.service.js
src/api/telephony/spare/telephony-spare.v6.service.js
src/api/telephony/telephony.service.js
src/api/xdsl/spare/xdsl-spare.service.js
src/api/xdsl/spare/xdsl-spare.v6.service.js
src/api/xdsl/xdsl.service.js

feat(spare): add spare management for telephony and xdsl

---

src/api/xdsl/modem/xdsl-modem.v6.service.js

feat(xdsl.modem): add reconfigure voip call for modem

---

src/api/xdsl/modem/xdsl-modem.v6.service.js

feat(xdsl.modem.exchange): add call for comfort exchange

---

src/api/vps/capabilities/vps-capabilities-aapi.service.js
src/api/vps/capabilities/vps-capabilities.service.js
src/api/vps/vps.service.js

Service related to new 2api endpoint : /vps/capabilities/{serviceName}

feat: add new capabilities 2api endpoint

---

src/api/ip/delegation/ip-delegation.v6.service.js

fix(ip.delegation): don't pass target as url param

---

src/api/vps/vps.v6.service.js

feat(vps): add termination routes

---

src/api/support/support.v6.service.js

92a506c - feat(support): add some new actions api bindings
ref: MANAGER-2803

feat(support): add some new actions api bindings

---

src/api/banner/banner.aapi.service.js
src/api/banner/banner.service.js

d89cfdd — feat: add banner aapi service

feat: add banner aapi service

---

src/api/dedicated/server/dedicated-server.service.js
src/api/dedicated/server/nic/dedicated-server.nic.service.js
src/api/dedicated/server/nic/dedicated-server.nic.v6.service.js
src/api/dedicated/server/vni/dedicated-server.vni.service.js
src/api/dedicated/server/vni/dedicated-server.vni.v6.service.js

Needed services for OLA feature
MANAGER-3263

feat: access dedicated network interfaces

---

src/api/vps/images/available/vps-images-available.v6.service.js

fix(vps): add cache for available images queries

---

src/api/cloudDb/enterprise/logs/logs.v6.service.js

feat(*): add enterprise db logs apis

---

src/api/telephony/carrierSip/carrier-sip.service.js
src/api/telephony/carrierSip/clusterDetails/carrier-sip-clusterDetails.service.js
src/api/telephony/carrierSip/clusterDetails/carrier-sip-clusterDetails.v6.service.js

feat(telephony): add carrier sip cluster details

---

src/api/telephony/carrierSip/carrier-sip.iceberg.js
src/api/telephony/carrierSip/carrier-sip.service.js

feat(carrier-sip): add iceberg use for get all carrier sip lines

---

.eslintrc.json
package.json
yarn.lock

build(eslint): add markdown plugin
- No quality check required.

build(eslint): add markdown plugin

---

src/api/cloud/project/cloud-project.service.js
src/api/cloud/project/lab/cloud-project-lab.service.js
src/api/cloud/project/lab/cloud-project-lab.v6.service.js

72d2087 — feat: add cloud lab api
* https://github.com/ovh-ux/manager/pull/1395

feat: add cloud lab api

---

src/api/telephony/portability/document/telephony-portability-document.service.js
src/api/telephony/portability/document/telephony-portability-document.v6.service.js
src/api/telephony/portability/telephony-portability.service.js

feat(telephony.portability.document): add upload document for portability

---

src/api/hosting/web/moduleList/web-moduleList.iceberg.service.js
src/api/hosting/web/moduleList/web-moduleList.service.js

feat(hosting): expose module list route through iceberg

---

src/api/vps/images/available/vps-images-available.v6.service.js

fix(vps): set different cache id for query request

---

src/api/domain/domain.service.js
src/api/domain/zone/domain-zone.service.js
src/api/domain/zone/domain-zone.v6.service.js
src/api/domain/zone/record/domain-zone-record.service.js
src/api/domain/zone/record/domain-zone-record.v6.service.js

feat(domain): add zone records

---

package.json
src/api/auth/auth.v6.service.js
src/api/me/order/me-order.v6.service.js
yarn.lock

4876a89 - build(dev-deps): upgrade some dev dependencies
7026264 - style: apply eslint rules
- https://github.com/kei-ito/rollup-plugin-glob-import/compare/v0.3.1...v0.4.4
- No quality check required.

Upgrade some dev dependencies

---

src/api/cloud/project/containerRegistry/cloud-project-containerRegistry.v6.service.js

30f7be0 - fix(cloud.project.container.registry): remove extra param
- No quality check required.
Signed-off-by: Antoine Leblanc <antoine.leblanc@corp.ovh.com>

fix(cloud.project.container.registry): remove extra param

---

src/api/order/cart/item/order-cart-item.v6.service.js

Ref : MANAGER-3320
Signed-off-by: Jérémy De-Cesare <jeremy.de-cesare@corp.ovh.com>

fix(order): fix query is array param

---

src/api/cloud/project/lab/cloud-project-lab.v6.service.js

a1837ed - fix(cloud.project.lab): remove body from activate action
ref: DTRSD-5803
Signed-off-by: Antoine Leblanc <antoine.leblanc@corp.ovh.com>

fix(cloud.project.lab): remove body from activate action

---

src/api/hosting/web/emailOption/hosting-web-email-option.service.js
src/api/hosting/web/emailOption/hosting-web-email-option.v6.service.js
src/api/hosting/web/web.service.js

Added hosting email option endpoints

feat(web): added hosting email option end points

---

src/api/order/email/domain/order-email-domain.service.js
src/api/order/email/domain/order-email-domain.v6.service.js
src/api/order/email/order-email.service.js
src/api/order/order.service.js

feat(email): add email offer upgrade end points

---

package.json
src/api/hosting/web/database/database.v6.service.js
src/api/hosting/web/emailOption/hosting-web-email-option.v6.service.js
src/api/order/email/domain/order-email-domain.v6.service.js
yarn.lock

1de63dd - build(dev-deps): upgrade some dev dependencies
9fe30e2 - style: apply eslint rules
- No quality check required.

Minor updates

---

src/api/msServices/account/account.service.js
src/api/msServices/account/mfa/mfa.service.js
src/api/msServices/account/mfa/mfa.v6.service.js
src/api/msServices/msServices.service.js
src/api/msServices/msServices.service.v6.js

ref: MANAGER-3014
ff443d3 — feat: add msServices mfa calls

feat: add msServices mfa calls

---

src/api/email/exchange/service/email-exchange-service.service.js
src/api/email/exchange/service/server/email-exchange-service-server.service.js
src/api/email/exchange/service/server/email-exchange-service-server.v6.service.js

ref: MANAGER-3014
d8f1961 — feat(email.exchange): add email exchange service server

feat(email.exchange): add email exchange service server

---

src/api/services/detach/services-detach.service.js
src/api/services/detach/services-detach.v6.service.js
src/api/services/services.service.js

ref: MANAGER-3328
Signed-off-by: Jérémy De-Cesare <jeremy.de-cesare@corp.ovh.com>

feat(services): add detach routes

---

src/api/xdsl/modem/xdsl-modem.v6.service.js

Retrieve price for modem exchange to replace the fixed labels into the manager
Ref: UXCT-230

feat(xdsl.modem): add endpoint to get price for modem exchange

---

src/api/hosting/web/extraSqlPerso/extraSqlPerso.service.js
src/api/hosting/web/extraSqlPerso/extraSqlPerso.v6.service.js
src/api/hosting/web/web.service.js

Signed-off-by: Frederic Espiau <frederic.espiau@corp.ovh.com>

feat(hosting): add extraSqlPerso path

---

src/api/cloud/cloud.aapi.service.js

feat(cloud): add pci deals route

---

src/api/dedicatedCloud/datacenter/backup/dedicatedCloud-datacenter-backup.v6.service.js

feat(dedicatedcloud-datacenter-backup): add backup offer capabilities

---

.eslintrc.json
src/ovh-api-services.module.js

fix(*): add missing imports

---

src/api/cloud/project/cloud-project.service.js
src/api/cloud/project/loadBalancer/loadBalancer.service.js
src/api/cloud/project/loadBalancer/loadBalancer.v6.service.js

Added PCI load balancer end points

feat(pci): added load balancer end points

---

src/api/dbaas/logs/logs.service.js
src/api/dbaas/logs/output/elasticsearch/elasticsearch.service.js
src/api/dbaas/logs/output/elasticsearch/kibana/kibana.aapi.service.js
src/api/dbaas/logs/output/elasticsearch/kibana/kibana.iceberg.service.js
src/api/dbaas/logs/output/elasticsearch/kibana/kibana.service.js
src/api/dbaas/logs/output/elasticsearch/kibana/kibana.v6.service.js
src/api/dbaas/logs/output/output.service.js

Hello,
This PR will add support to new Kibana endpoints available on dbaas/logs namespace.
Thanks for your time on this subject.
Signed-off-by: Pierre De Paepe <pierre.de-paepe@ovhcloud.com>

feat(cloud.logs): add kibana endpoints

---

src/api/cloud/project/kube/cloud-project-kube.v6.service.js

Addition of kubeconfig reset API

fix(kube): kubeconfig reset api addition

---

src/api/dbaas/logs/output/elasticsearch/kibana/kibana.v6.service.js

Hello,
This PR to handle a new api endpoint that will let users to update their Kibana instances.
Thanks for your time on this.
Signed-off-by: Pierre De Paepe <pierre.de-paepe@ovhcloud.com>

feat(cloud.logs): handle kibana update endpoint

---

src/api/dbaas/logs/role/permission/role-permission.v6.service.js

Hello,
This PR will allow users to declare Kibana permissions on a given LDP role.
Thanks for your time on this.
Signed-off-by: Pierre De Paepe <pierre.de-paepe@ovhcloud.com>

feat(cloud.logs): support kibana permission on role

---

src/api/cloud/project/ai/training/job/cloud-project-ai-training-job.v6.service.js

feat(cloud.project.training): add training job logs

---

src/api/xdsl/xdsl.v6.service.js

Add endpoints to retrieve available meetings and to order one for xDSL customer.
Ref: UXCT-194

feat(xdsl.meetings): add endpoints to retrieve and select meeting

---

src/api/cloud/project/ai/capabilities/serving/backend/cloud-project-ai-capabilities-serving-backend.service.js
src/api/cloud/project/ai/capabilities/serving/backend/cloud-project-ai-capabilities-serving-backend.v6.service.js
src/api/cloud/project/ai/capabilities/serving/cloud-project-ai-capabilities-serving.service.js
src/api/cloud/project/ai/capabilities/serving/framework/cloud-project-ai-capabilities-serving-framework.service.js
src/api/cloud/project/ai/capabilities/serving/framework/cloud-project-ai-capabilities-serving-framework.v6.service.js

Add serving framework and backend capabilities

feat(cloud.project.serving): add serving framework and backend capabilities

---

src/api/xdsl/modem/availableACSBackend/xdsl-modem-availableACSBackend.service.js
src/api/xdsl/modem/availableACSBackend/xdsl-modem-availableACSBackend.v6.service.js
src/api/xdsl/modem/xdsl-modem.service.js

feat(xdsl.modem): add endpoint to retrieve available ACS backend for modem

---

src/api/pack/xdsl/move/pack-xdsl-move.v6.service.js

Ref: UXCT-329
Signed-off-by: Stephanie Moallic <stephanie.moallic@corp.ovh.com>

feat(pack.xdsl.move): add endpoint for service to delete

---

src/api/connectivity/eligibility/search/connectivity-eligibility-search.v6.service.js

Resolve pending return on the call API
Ref: UXCT-323
Signed-off-by: Stephanie Moallic <stephanie.moallic@corp.ovh.com>

fix(connectivity.eligibility): rework on building details call api

---

src/api/connectivity/eligibility/connectivity-eligibility.v6.service.js

Ref: UXCT-388
Signed-off-by: Stephanie Moallic <stephanie.moallic@corp.ovh.com>

feat(connectivity): add 2 eligibility endpoints for partners

---

src/api/cloud/project/ai/capabilities/training/region/resource/cloud-project-ai-capabilities-training-region-resource.service.js
src/api/cloud/project/ai/capabilities/training/region/resource/cloud-project-ai-capabilities-training-region-resource.v6.service.js

Signed-off-by: Christophe Rannou <christophe.rannou@ovhcloud.com>
Required for Manager PR: https://github.com/ovh/manager/pull/4604

feat(cloud.project.ai.training): add capability resource service

---

src/api/telecom/sidebar/telecom-sidebar.service.js

339c596 - fix(telecom.sidebar): restore `OvhApiTelecomSidebar` service
- #330 
Signed-off-by: Antoine Leblanc <antoine.leblanc@ovhcloud.com>

fix(telecom.sidebar): restore `OvhApiTelecomSidebar` service

---

src/api/me/availableAutomaticPaymentMeans/me-availableAutomaticPaymentMeans.service.js
src/api/me/availableAutomaticPaymentMeans/me-availableAutomaticPaymentMeans.v6.service.js
src/api/me/me.service.js

ref: MANAGER-9639
BREAKING-CHANGE: drop me.AvailableAutomaticPaymentMeans method
Signed-off-by: Anoop <anooparveti@gmail.com>

refactor: remove deprecated `/me/avaiableAutomaticPaymentMeans` method
